# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: elastic-search

elasticsearch:
  instances:
    - version: 8.7.1
      storage:
        size: 30Gi
  storage:
    storageClass: managed-premium
