apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: dummy
  labels:
    app: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      nodeSelector:
        app: cluster-paas
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "cluster-paas"
        effect: "NoSchedule"
      containers:
        - name: mynginx
          image: mcr.microsoft.com/cbl-mariner/base/nginx:1.22
          resources:
            requests:
              cpu: 10m
              memory: 5242880
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: index-html
          configMap:
            name: nginx-index-html
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: dummy
spec:
  type: LoadBalancer
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mynginx-pdb
  namespace: dummy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mynginx
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mynginx-so
  namespace: dummy
spec:
  scaleTargetRef:
    name: mynginx
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: '80'