apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: dummy
  labels:
    app: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      nodeSelector:
        app: cluster-paas
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "cluster-paas"
        effect: "NoSchedule"
      containers:
        - name: mynginx
          image: mcr.microsoft.com/cbl-mariner/base/nginx:1.22
          resources:
            requests:
              cpu: 10m
              memory: 5242880
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: index-html
          configMap:
            name: nginx-index-html