---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-sample
  namespace: flux-system
spec:
  targetNamespace: sample
  storageNamespace: sample
  chart:
    spec:
      chart: ./charts/samples
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
    timeout: 5m
