apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: dummy
spec:
  type: LoadBalancer
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80