apiVersion: v1
kind: Namespace
metadata:
  name: dummy
  labels:
    toolkit.fluxcd.io/tenant: software-stamp
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mynginx-vpa
  namespace: dummy
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynginx
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 5Mi
        maxAllowed:
          cpu: 1
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mynginx-so
  namespace: dummy
spec:
  scaleTargetRef:
    name: mynginx
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: '80'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: dummy
  labels:
    app: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx
          image: mcr.microsoft.com/cbl-mariner/base/nginx:1.22
          resources:
            requests:
              cpu: 10m
              memory: 5242880
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  namespace: dummy
spec:
  type: LoadBalancer
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
