apiVersion: v1
kind: Namespace
metadata:
  name: dummy
  labels:
    toolkit.fluxcd.io/tenant: software-stamp
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mynginx-vpa
  namespace: dummy
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynginx
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 5Mi
        maxAllowed:
          cpu: 1
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: dummy
  labels:
    app: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx
          image: mcr.microsoft.com/cbl-mariner/base/nginx:1.22
          