{{- $elasticInstances := .Values.elasticInstances | default 1 | int }}
{{- range $i := until $elasticInstances }}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  version: {{ $.Values.elasticVersion }}
  elasticsearchRef:
    name: elasticsearch-{{ $i }}
  count: 1
  config:
    elasticsearch.serviceAccountToken: null  # Explicitly set to null to disable
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch-{{ $i }}-es-http.{{ $.Release.Namespace }}.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: elastic-username-{{ $i }}
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: elastic-password-{{ $i }}
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: elastic-key-{{ $i }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-env-{{ $i }}
  namespace: {{ $.Release.Namespace }}
data:
  XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
{{- end }}
