apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    {{- include "sample.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}